/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestion_tienda.h"


void
gestion_usuarios_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	usuario  registrar_usuario_1_arg;
	lista_producto  *result_2;
	char *imprimir_productos_1_arg;
	bool_t  *result_3;
	codigo  agregrar_a_la_lista_de_compras_1_arg;
	lista_compras  *result_4;
	char *imprimir_listas_compras_1_arg;
	bool_t  *result_5;
	datos_credenciales  abrir_sesion_1_arg;
	factura  *result_6;
	char *imprimir_factura_1_arg;
	codigo obj_codigo;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_usuarios, gestion_usuarios_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	
	
	int opcion=0;
	int bandera1=0,opcion2=0,bandera3=0;
	usuario obj_usuario;
	datos_credenciales obj_datos_credenciales;
	
	
	do{
	
		printf("\n============ MENU PRINCIPAL ============\n");
		printf("\n *	1. Registrar usuario.          *\n");
		printf("\n *	2. Iniciar sesion.             *\n");
		printf("\n *	3. Salir.                      *\n");
		printf("========== INGRESE UNA OPCION ==========\n\n");
		scanf("%d",&opcion);
		
		switch(opcion){
		
			case 1:
				printf("---------Registro de usuario---------\n");
				printf("Ingrese el nombres del usuario: ");
				scanf("%s",obj_usuario.full_name);
				printf("Ingrese el apellidos del usuario: ");
				scanf("%s",obj_usuario.last_name);
				printf("Ingrese el id del usuario: ");
				scanf("%s",obj_usuario.id);
				printf("Ingrese el username del usuario: ");
				scanf("%s",obj_usuario.user_name);
				printf("Ingrese el password del usuario: ");
				scanf("%s",obj_usuario.password);
				result_1 = registrar_usuario_1(&obj_usuario, clnt);
				if (result_1 == (bool_t *) NULL) {
					clnt_perror (clnt, "call failed");
				}else if(*result_1 == TRUE){
					printf("Usuario registrado con exito\n");
					bandera1 = 1;
				}
				else{
					printf("No se pudo registrar el usuario\n");
				}
			break;
			
			
			
			case 2:
				if(bandera1 == 0){
					printf("Tienes que resgistrar un usuario\n");
					break;
				}
				else{
					printf("Ingrese el usuario: ");
					scanf("%s",obj_datos_credenciales.user_name);
					printf("Ingrese el password: ");
					scanf("%s",obj_datos_credenciales.password);
					result_5 = abrir_sesion_1(&obj_datos_credenciales, clnt);
					if (result_5 == (bool_t *) NULL) {
						clnt_perror (clnt, "call failed");
					}else if(*result_5 == TRUE){
						do
						{
							
							printf("\n============= MENU TIENDA =============\n");
							printf("\n *	1. Agregar a la lista de compas.*\n");
							printf("\n *	2. Consultar lista de compras.  *\n");
							printf("\n *	3. Generar factura.             *\n");
							printf("\n *	4. Salir.                       *\n");
							printf("========== INGRESE UNA OPCION ==========\n\n");
							scanf("%d",&opcion2);
							
							getchar();
							
							switch(opcion2){
								case 1:
									printf("\n ====== Agregar Producto ====== \n");
									result_2 = imprimir_productos_1((void*)&imprimir_productos_1_arg, clnt);
									if (result_2 == (lista_producto *) NULL) {
										clnt_perror (clnt, "call failed");
									}

									nodo_producto *obj_producto_actual = result_2 -> cabeza_producto;

									printf("\n ======== Lista de productos de la tienda ======= \n");
									printf("\n Id\tNombre\tValor\n");

									while(obj_producto_actual != NULL)
									{
										printf("\n %s\t%s\t%.2f", obj_producto_actual-> obj_producto.id,
									        obj_producto_actual -> obj_producto.nombre,
									        obj_producto_actual -> obj_producto.valor);
										obj_producto_actual= obj_producto_actual -> 											siguiente;
									}
									printf("\nIngresa el id del producto que deseas comprar: ");
									scanf("%s",obj_codigo.id);
									
									
									result_3 = agregrar_a_la_lista_de_compras_1(&obj_codigo, clnt);
									if (result_3 == (bool_t *) NULL) {
										clnt_perror (clnt, "call failed");
									}
									else if(*result_3 == TRUE){
										bandera3=1;
										printf("Se ha agregado el producto a la lista de compras\n");
									}
									else{
										printf("No se ha agregado el producto a la lista de compras\n");
									}
					                		
								break;
								
								case 2:
								
								if(bandera3 == 0){
									printf("No se ha registrados productos aun\n");
									break;
								}
								
								result_4 = imprimir_listas_compras_1((void*)&imprimir_listas_compras_1_arg, clnt);
									if (result_4 == (lista_compras *) NULL) {
										clnt_perror (clnt, "call failed");
									}
									
								
									nodo_producto *obj_producto_actual2 = result_4 -> obj_producto_cabeza;
									
									printf("\n ======== Lista de productos que se va a comprar======= \n");
									printf("\n Id\tNombre\tValor\n");

									while(obj_producto_actual2 != NULL)
									{
										printf("\n %s\t%s\t%.2f", obj_producto_actual2-> obj_producto.id,
									        obj_producto_actual2 -> obj_producto.nombre,
									        obj_producto_actual2 -> obj_producto.valor);
										obj_producto_actual2= obj_producto_actual2 -> 											siguiente;
									}	
								break;
								
								case 3:
								
									if(bandera3 == 0){
										printf("No se ha registrados productos aun\n");
										break;
									}
								
									result_6 = imprimir_factura_1((void*)&imprimir_factura_1_arg, clnt);
									if (result_6 == (factura *) NULL) {
										clnt_perror (clnt, "call failed");
									}
									
									
									lista_compras *obj_lista_compras_f = result_6->obj_compra;
								 nodo_producto * obj_producto_actual3 = obj_lista_compras_f ->obj_producto_cabeza;
									
									
									printf("\n============== FACTURA ==============\n");
									printf("Id: %d\n",result_6->id);
									printf("Lista de productos comprados:\n");	
									printf("\n Id\tNombre\tValor\n");
									while(obj_producto_actual3 != NULL)
									{
										printf("\n %s\t%s\t%.2f", obj_producto_actual3-> obj_producto.id,
									        obj_producto_actual3 -> obj_producto.nombre,
									        obj_producto_actual3 -> obj_producto.valor);
										obj_producto_actual3= obj_producto_actual3 -> siguiente;
									}
									printf("\nCantidad de productos: %d\n",(int)result_6->cantidad_productos);
									printf("Descuento: %.02f\n",result_6->descuento);
									printf("Total a pagar: %.02f\n",result_6->total_compra);
									printf("\n=====================================\n");

								break;
							}
							
						}while(opcion2!=4);
					}
					else{
						printf("Credenciales incorrectas\n");
					}
				}
			break;
			
				
		}
	
	}while(opcion != 3);

	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_usuarios_1 (host);
exit (0);
}
