/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestion_tienda.h"

bool_t
xdr_usuario (XDR *xdrs, usuario *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->full_name, max_name,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->last_name, max_lastname,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->id, max_id,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->user_name, max_user_name,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->password, max_password,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_usuario (XDR *xdrs, nodo_usuario *objp)
{
	register int32_t *buf;

	 if (!xdr_usuario (xdrs, &objp->obj_usuario))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->siguiente, sizeof (nodo_usuario), (xdrproc_t) xdr_nodo_usuario))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lista_usuario (XDR *xdrs, lista_usuario *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->cabeza_usuario, sizeof (nodo_usuario), (xdrproc_t) xdr_nodo_usuario))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tamanio))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_credenciales (XDR *xdrs, datos_credenciales *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->user_name, max_user_name,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->password, max_password,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto (XDR *xdrs, producto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->id, max_id,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, max_name,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valor))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_producto (XDR *xdrs, nodo_producto *objp)
{
	register int32_t *buf;

	 if (!xdr_producto (xdrs, &objp->obj_producto))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->siguiente, sizeof (nodo_producto), (xdrproc_t) xdr_nodo_producto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lista_producto (XDR *xdrs, lista_producto *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->cabeza_producto, sizeof (nodo_producto), (xdrproc_t) xdr_nodo_producto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tamanio))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lista_compras (XDR *xdrs, lista_compras *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->obj_producto_cabeza, sizeof (nodo_producto), (xdrproc_t) xdr_nodo_producto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tamanio))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_factura (XDR *xdrs, factura *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->obj_compra, sizeof (lista_compras), (xdrproc_t) xdr_lista_compras))
		 return FALSE;
	 if (!xdr_usuario (xdrs, &objp->obj_usuario))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->total_compra))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->cantidad_productos))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->descuento))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_codigo (XDR *xdrs, codigo *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->id, max_id,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
