/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTION_TIENDA_H_RPCGEN
#define _GESTION_TIENDA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define max_name 30
#define max_lastname 30
#define max_id 20
#define max_user_name 20
#define max_password 30
#define max_rol 15

struct usuario {
	char full_name[max_name];
	char last_name[max_lastname];
	char id[max_id];
	char user_name[max_user_name];
	char password[max_password];
};
typedef struct usuario usuario;

struct nodo_usuario {
	usuario obj_usuario;
	struct nodo_usuario *siguiente;
};
typedef struct nodo_usuario nodo_usuario;

struct lista_usuario {
	nodo_usuario *cabeza_usuario;
	int tamanio;
};
typedef struct lista_usuario lista_usuario;

struct datos_credenciales {
	char user_name[max_user_name];
	char password[max_password];
};
typedef struct datos_credenciales datos_credenciales;

struct producto {
	char id[max_id];
	char nombre[max_name];
	float valor;
};
typedef struct producto producto;

struct nodo_producto {
	producto obj_producto;
	struct nodo_producto *siguiente;
};
typedef struct nodo_producto nodo_producto;

struct lista_producto {
	nodo_producto *cabeza_producto;
	int tamanio;
};
typedef struct lista_producto lista_producto;

struct lista_compras {
	nodo_producto *obj_producto_cabeza;
	int tamanio;
};
typedef struct lista_compras lista_compras;

struct factura {
	int id;
	lista_compras *obj_compra;
	usuario obj_usuario;
	float total_compra;
	float cantidad_productos;
	float descuento;
};
typedef struct factura factura;

struct codigo {
	char id[max_id];
};
typedef struct codigo codigo;

#define gestion_usuarios 0x20000020
#define gestion_usuarios_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrar_usuario 1
extern  bool_t * registrar_usuario_1(usuario *, CLIENT *);
extern  bool_t * registrar_usuario_1_svc(usuario *, struct svc_req *);
#define imprimir_productos 2
extern  lista_producto * imprimir_productos_1(void *, CLIENT *);
extern  lista_producto * imprimir_productos_1_svc(void *, struct svc_req *);
#define agregrar_a_la_lista_de_compras 3
extern  bool_t * agregrar_a_la_lista_de_compras_1(codigo *, CLIENT *);
extern  bool_t * agregrar_a_la_lista_de_compras_1_svc(codigo *, struct svc_req *);
#define imprimir_listas_compras 4
extern  lista_compras * imprimir_listas_compras_1(void *, CLIENT *);
extern  lista_compras * imprimir_listas_compras_1_svc(void *, struct svc_req *);
#define abrir_sesion 5
extern  bool_t * abrir_sesion_1(datos_credenciales *, CLIENT *);
extern  bool_t * abrir_sesion_1_svc(datos_credenciales *, struct svc_req *);
#define imprimir_factura 6
extern  factura * imprimir_factura_1(void *, CLIENT *);
extern  factura * imprimir_factura_1_svc(void *, struct svc_req *);
extern int gestion_usuarios_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrar_usuario 1
extern  bool_t * registrar_usuario_1();
extern  bool_t * registrar_usuario_1_svc();
#define imprimir_productos 2
extern  lista_producto * imprimir_productos_1();
extern  lista_producto * imprimir_productos_1_svc();
#define agregrar_a_la_lista_de_compras 3
extern  bool_t * agregrar_a_la_lista_de_compras_1();
extern  bool_t * agregrar_a_la_lista_de_compras_1_svc();
#define imprimir_listas_compras 4
extern  lista_compras * imprimir_listas_compras_1();
extern  lista_compras * imprimir_listas_compras_1_svc();
#define abrir_sesion 5
extern  bool_t * abrir_sesion_1();
extern  bool_t * abrir_sesion_1_svc();
#define imprimir_factura 6
extern  factura * imprimir_factura_1();
extern  factura * imprimir_factura_1_svc();
extern int gestion_usuarios_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_usuario (XDR *, usuario*);
extern  bool_t xdr_nodo_usuario (XDR *, nodo_usuario*);
extern  bool_t xdr_lista_usuario (XDR *, lista_usuario*);
extern  bool_t xdr_datos_credenciales (XDR *, datos_credenciales*);
extern  bool_t xdr_producto (XDR *, producto*);
extern  bool_t xdr_nodo_producto (XDR *, nodo_producto*);
extern  bool_t xdr_lista_producto (XDR *, lista_producto*);
extern  bool_t xdr_lista_compras (XDR *, lista_compras*);
extern  bool_t xdr_factura (XDR *, factura*);
extern  bool_t xdr_codigo (XDR *, codigo*);

#else /* K&R C */
extern bool_t xdr_usuario ();
extern bool_t xdr_nodo_usuario ();
extern bool_t xdr_lista_usuario ();
extern bool_t xdr_datos_credenciales ();
extern bool_t xdr_producto ();
extern bool_t xdr_nodo_producto ();
extern bool_t xdr_lista_producto ();
extern bool_t xdr_lista_compras ();
extern bool_t xdr_factura ();
extern bool_t xdr_codigo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTION_TIENDA_H_RPCGEN */
