/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestion_tienda.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
gestion_usuarios_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		usuario registrar_usuario_1_arg;
		codigo agregrar_a_la_lista_de_compras_1_arg;
		datos_credenciales abrir_sesion_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case registrar_usuario:
		_xdr_argument = (xdrproc_t) xdr_usuario;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) registrar_usuario_1_svc;
		break;

	case imprimir_productos:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_lista_producto;
		local = (char *(*)(char *, struct svc_req *)) imprimir_productos_1_svc;
		break;

	case agregrar_a_la_lista_de_compras:
		_xdr_argument = (xdrproc_t) xdr_codigo;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) agregrar_a_la_lista_de_compras_1_svc;
		break;

	case imprimir_listas_compras:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_lista_compras;
		local = (char *(*)(char *, struct svc_req *)) imprimir_listas_compras_1_svc;
		break;

	case abrir_sesion:
		_xdr_argument = (xdrproc_t) xdr_datos_credenciales;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) abrir_sesion_1_svc;
		break;

	case imprimir_factura:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_factura;
		local = (char *(*)(char *, struct svc_req *)) imprimir_factura_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (gestion_usuarios, gestion_usuarios_version);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_usuarios, gestion_usuarios_version, gestion_usuarios_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (gestion_usuarios, gestion_usuarios_version, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_usuarios, gestion_usuarios_version, gestion_usuarios_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (gestion_usuarios, gestion_usuarios_version, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
