/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "gestion_tienda.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

bool_t *
registrar_usuario_1(usuario *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, registrar_usuario,
		(xdrproc_t) xdr_usuario, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

lista_producto *
imprimir_productos_1(void *argp, CLIENT *clnt)
{
	static lista_producto clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, imprimir_productos,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_lista_producto, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
agregrar_a_la_lista_de_compras_1(codigo *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, agregrar_a_la_lista_de_compras,
		(xdrproc_t) xdr_codigo, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

lista_compras *
imprimir_listas_compras_1(void *argp, CLIENT *clnt)
{
	static lista_compras clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, imprimir_listas_compras,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_lista_compras, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
abrir_sesion_1(datos_credenciales *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, abrir_sesion,
		(xdrproc_t) xdr_datos_credenciales, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

factura *
imprimir_factura_1(void *argp, CLIENT *clnt)
{
	static factura clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, imprimir_factura,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_factura, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
